import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose weights you want
  variable: "--font-open-sans", // optional for Tailwind CSS
});

export const metadata: Metadata = {
  title: "SameshAI",
  description: "Generated by create next app value",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} ${openSans.className}`}>
        {children}
      </body>
    </html>
  );
}
